spring.application.name=food-care

# URL de conexão (ajuste o nome do seu banco após a barra)
spring.datasource.url=jdbc:mysql://localhost:3306/food_care_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=31@Mafuyu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate - Dialeto para MySQL 8+
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Estratégia de atualização do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Documentação Swagger Spring Doc
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
